export const DANG_NHAP="DANG_NHAP";
export const DANG_NHAP_DATA="DANG_NHAP_DATA";
export const DANG_NHAP_MESSAGE="DANG_NHAP_MESSAGE";
export const GET_LIST_ALL_USER="GET_LIST_ALL_USER";
export const UPDATE_USER="UPDATE_USER";
export const DELETE_USER="DELETE_USER";
export const DELETE_USER_MESSAGE="DELETE_USER_MESSAGE";